In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

dates = pd.date_range(
    start="2026-01-01",
    periods=90,
    freq="D"
)

traffic = np.random.normal(18000, 1200, 90).astype(int)

conversion_rate = np.random.normal(0.022, 0.002, 90)

orders = (traffic * conversion_rate).astype(int)

revenue_per_order = np.random.normal(2500, 150, 90)

revenue = (orders * revenue_per_order).astype(int)

marketing_cost = np.random.normal(40000, 3000, 90).astype(int)

refunds = np.random.normal(20, 5, 90).astype(int)

df = pd.DataFrame({
    "date": dates,
    "traffic": traffic,
    "orders": orders,
    "revenue": revenue,
    "marketing_cost": marketing_cost,
    "refunds": refunds
})

df.head()

        date  traffic  orders  revenue  marketing_cost  refunds
0 2026-01-01    18596     412  1068666           44323       22
1 2026-01-02    17834     426  1010227           35692       27
2 2026-01-03    18777     386   902995           43489       19
3 2026-01-04    19827     423  1088112           40030       22
4 2026-01-05    17719     375   924930           37055       23

In [2]:
df.loc[40, "traffic"] = 40000

In [3]:
df.loc[60, "revenue"] = 45000

In [4]:
df.loc[75, "refunds"] = 100

In [5]:
df.loc[[40, 60, 75]]

         date  traffic  orders  revenue  marketing_cost  refunds
40 2026-02-10    40000     356  1013602           39346       12
60 2026-03-02    17424     392    45000           39963       30
75 2026-03-17    18986     433  1051048           40696      100

In [7]:
df["Conversion rate"] = (df["orders"]/df["traffic"] *100)

In [8]:
df.head()

,date,traffic,orders,revenue,marketing_cost,refunds,Conversion rate
0,2026-01-01,18596,412,1068666,44323,22,2.215530
1,2026-01-02,17834,426,1010227,35692,27,2.388696
2,2026-01-03,18777,386,902995,43489,19,2.055706
3,2026-01-04,19827,423,1088112,40030,22,2.133454
4,2026-01-05,17719,375,924930,37055,23,2.116372

In [10]:
df.to_csv("/Users/shreedharkokate/Desktop/business-anomaly-agent/data/shree_market.csv" , index= False)